config/routes.rb
Rails.application.routes.draw do
  mount Dashing::Engine, at: Dashing.config.engine_path
  root :to => 'admin/sessions#index'
  get 'users/unique_email' => 'admin/users#unique_email'
  # get "log_in" => "users#new", :as => "log_in"

  # Sign In URLs for users
  # get     '/sign_in',         to: "public/user_sessions#sign_in",         as:  :sign_in
  # post    '/create_session',  to: "public/user_sessions#create_session",  as:  :create_session
  # Logout Url
  # delete  '/sign_out' ,       to: "public/user_sessions#sign_out",        as:  :sign_out

  namespace :admin do
    resources :users
    resources :sessions
    resources :birthdays
    resources :events
    resources :generals
    resources :newjoiners
    resources :anniversarrys
    resources :achievements
    resources :hrs 
    resources :wallboards
      
    get :admin_role
    resources :dashboards do
      mount Dashing::Engine, at: Dashing.config.engine_path
      resources :dashboard_widgets
    end
  end
  # post "pop_up" => "admin/dashboards#pop_up"
  # ------------
  # User pages
  # ------------

  # namespace :users do
  #   get   '/dashboard',         to: "dashboard#index",  as:   :dashboard
  #   get   '/profile',           to: "profile#index",    as:   :profile
  #   get   '/edit',              to: "profile#edit",     as:   :edit
  #   put   '/update',            to: "profile#update",   as:   :update

  #   resources :images do
  #     member do
  #       put :crop
  #     end
  #   end
  # end

end

app/controllers/dashing/dashboards_controller.rb
module Dashing
  class DashboardsController < ApplicationController
    require 'octokit'
    require 'httparty'
    require 'net/http'
    require 'json'
    require 'jira'
    require 'time'
    require 'newrelic_api'
    require 'open-uri'
    require 'cgi'

    include GitHub
    include CodeClimate
    include Jira
    include Jenkins
    include Newrelic
    include BurnDownChart
    include QwinixUpdatesJob

    before_filter :check_dashboard_name, only: :show

    rescue_from ActionView::MissingTemplate, with: :template_not_found

    def index
      get_the_job_done(params[:dashboard_id])
      render file: dashboard_path(Dashing.config.default_dashboard || Dashing.first_dashboard || ''), layout: Dashing.config.dashboard_layout_path
    end

    def show
      render file: dashboard_path(params[:name]), layout: Dashing.config.dashboard_layout_path
    end

    private

    def check_dashboard_name
      raise 'bad dashboard name' unless params[:name] =~ /\A[a-zA-z0-9_\-]+\z/
    end

    def dashboard_path(name)
      Dashing.config.dashboards_views_path.join(name)
    end

    def template_not_found
      raise "Count not find template for dashboard '#{params[:name]}'. Define your dashboard in #{dashboard_path('')}"
    end

    def get_the_job_done(id)
      @json_obj = []
      if id != nil
        dashboard = Dashboard.find id
        dashboard.dashboard_widgets.each do |dash_wid|
          @json_obj << JSON.parse(dash_wid.to_json).compact
        end   
        @json_obj.each do |obj|
          case (Widget.find obj["widget_id"]).name 
          when "Github-Open-PR" 
            github_open_pr_job(obj) if obj["status"] == "configured"
          when "Github-Closed-PR" 
            github_closed_pr_job(obj) if obj["status"] == "configured"
          when "GPA" 
            gpa(obj) if obj["status"] == "configured"
          when "Github-Status" 
            github_status(obj) if obj["status"] == "configured"
          when "Sprint-progress" 
            sprint_progress(obj) if obj["status"] == "configured"
          when "Sprint-remaning-days" 
            sprint_remaining_days(obj) if obj["status"] == "configured"
          when "Jira Stories Details" 
            number_of_open_issues(obj) if obj["status"] == "configured" 
          when "Build-test" 
            jenkins_build_status(obj) if obj["status"] == "configured"
          when "Github-Last-10-Commits" 
            github_commits(obj) if obj["status"] == "configured"
          when "Error-Rate" 
            newrelic_job(obj) if obj["status"] == "configured"
          when "Response-Time" 
            newrelic_job(obj) if obj["status"] == "configured"
          when "Burn Down Chart" 
            BurnDown.burn_down_chart(obj) if obj["status"] == "configured"
          end
        end
      else
       view_qwinix_updates
      end
    end
  end
end

app/controllers/dashing/events_controller.rb
module Dashing
  class EventsController < ApplicationController
    include ActionController::Live
    include ApplicationHelper

    def index
      response.headers['Content-Type']      = 'text/event-stream'
      response.headers['X-Accel-Buffering'] = 'no'

      @redis = Dashing.redis
      @redis.psubscribe("#{Dashing.config.redis_namespace}.*") do |on|
        on.pmessage do |pattern, event, data|
          response.stream.write("data: #{data}\n\n")
        end
      end
    rescue IOError
      logger.info "[Dashing][#{Time.now.utc.to_s}] Stream closed"
    ensure
      @redis.quit
      response.stream.close
    end

  end
end

app/controllers/dashing/widgets_controller.rb
module Dashing
  class WidgetsController < ApplicationController
    include ApplicationHelper

    before_filter :check_accessibility, only: :update
    before_filter :check_widget_name,   only: [:show, :update]
    before_filter :prepend_view_paths,  only: :show

    rescue_from ActionView::MissingTemplate, with: :template_not_found

    def show
      render file: widget_path, layout: false
    end

    def update
      data = params[:widget] || {}
      hash = data.merge(id: params[:name], updatedAt: Time.now.utc.to_i)
      Dashing.redis.publish("#{Dashing.config.redis_namespace}.create", hash.to_json)

      render nothing: true
    end

    private

    def check_widget_name
      raise 'bad widget name' unless params[:name] =~ /\A[a-zA-z0-9_\-]+\z/
    end

    def widget_path
      params[:name]
    end

    def prepend_view_paths
      prepend_view_path main_app_view_path
    end

    def main_app_view_path
      Dashing.config.widgets_views_path
    end

    def template_not_found
      raise "Count not find template for widget #{params[:name]}. Define your widget in #{main_app_view_path}"
    end

  end
end

app/views/layouts/dashing/_flash_messages.html.erb
<%
if request.xhr?
	flash_message = flash.now[:success] || flash.now[:notice] || flash.now[:alert] || flash.now[:error]
	style_classes = ""
else
	style_classes = ""
	flash_message = flash[:success] || flash[:notice] || flash[:alert] || flash[:error]
end
cls_name = "alert-info"
cls_name = 'alert-success' if flash.now[:success] || flash[:success]
cls_name = 'alert-warning' if flash.now[:alert] || flash[:alert]
cls_name = 'alert-danger' if flash.now[:error] || flash[:error]

flash_message = flash_message.strip if flash_message

%>

<% unless flash_message.blank? %>
<div id = "flash">
	<div class="<%= style_classes %> alert <%= cls_name %> fade in mb-10" data-alert="alert">
		<a class="close" data-dismiss='alert' href="#">×</a>
		<p><%= flash_message %></p>
	</div>
</div>
<% end %>

app/views/layouts/dashing/_header.html.erb
<div class="container">
  <div class="navbar-header">
    <button data-target=".bs-navbar-collapse" data-toggle="collapse" type="button" class="navbar-toggle collapsed">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div id="logo">
      <a class="navbar-brand" > </a>
    </div>

  </div>
  <nav class="collapse navbar-collapse bs-navbar-collapse">
    <ul class="nav navbar-nav">
      <!-- navbar lists -->
      <li>
        <% if current_page?(admin_dashboards_path) %>
        <%= link_to  admin_dashboards_path,:class=>"border-left border-right",  :class=>"active" do %>
        <i class="fa fa-tachometer header-icons"></i><br />
        manage dashboard
        <% end %>
        <% else %>
        <%= link_to  admin_dashboards_path,:class=>"border-left border-right" do %>
        <i class="fa fa-tachometer header-icons"></i><br />
        manage dashboard
        <% end %>
        <% end %>
      </li>
      <li>
        <% if current_page?(admin_users_path) %>
        <%= link_to  admin_users_path, :class =>"border-right active" do %>
        <i class="fa fa-cogs header-icons"></i> <br />
        manage users
        <% end %>
        <% else %>
        <%= link_to  admin_users_path, :class =>"border-right" do %>
        <i class="fa fa-cogs header-icons"></i> <br />
        manage users
        <% end %>
        <% end %>
      </li>
      <li>
        <% if current_page?(admin_hrs_path) %>
        <%= link_to    admin_hrs_path, :class =>"border-right active" do %>
        <i class="fa fa-cogs header-icons"></i> <br />
        hr
        <% end %>
        <% else %>
        <%= link_to  admin_hrs_path, :class =>"border-right" do %>
        <i class="fa fa-cogs header-icons"></i> <br />
        hr
        <% end %>
        <% end %>
      </li>
    </ul>
    <!-- user dropdown -->
    <ul class="nav navbar-nav navbar-right">
     
        </li>
        <li style="margin-top: 25px;"><%= link_to "Sign Out", admin_session_path(current_user), method: :delete %></li>
      </ul>
    </nav>
  </div>

app/views/layouts/dashing/dashboard.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><%= yield :title %></title>

  <%= javascript_include_tag 'dashing/application' %>
  <%= stylesheet_link_tag 'dashing/application' %>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700' rel='stylesheet' type='text/css'>
  <link rel="icon" href="/favicon.ico">
</head>
<body>
  <div id="container">
    <%= yield %>
  </div>

  <% if Rails.env.development? %>
  <div id="saving-instructions">
    <p>Paste the following at the top of <i><%= params[:dashboard] %>.erb</i></p>
    <textarea id="gridster-code"></textarea>
  </div>
  <a href="#saving-instructions" id="save-gridster">Save this layout</a>
  <% end %>
</body>
</html>