config/routes.rb
Rails.application.routes.draw do
  mount Dashing::Engine, at: Dashing.config.engine_path
  root :to => 'admin/sessions#index'
  get 'users/unique_email' => 'admin/users#unique_email'
  # get "log_in" => "users#new", :as => "log_in"

  # Sign In URLs for users
  # get     '/sign_in',         to: "public/user_sessions#sign_in",         as:  :sign_in
  # post    '/create_session',  to: "public/user_sessions#create_session",  as:  :create_session
  # Logout Url
  # delete  '/sign_out' ,       to: "public/user_sessions#sign_out",        as:  :sign_out

  namespace :admin do
    resources :users
    resources :sessions
    resources :birthdays
    resources :events
    resources :generals
    resources :newjoiners
    resources :anniversarrys
    resources :achievements
    resources :hrs 
    resources :wallboards
      
    get :admin_role
    resources :dashboards do
      mount Dashing::Engine, at: Dashing.config.engine_path
      resources :dashboard_widgets
    end
  end
  # post "pop_up" => "admin/dashboards#pop_up"
  # ------------
  # User pages
  # ------------

  # namespace :users do
  #   get   '/dashboard',         to: "dashboard#index",  as:   :dashboard
  #   get   '/profile',           to: "profile#index",    as:   :profile
  #   get   '/edit',              to: "profile#edit",     as:   :edit
  #   put   '/update',            to: "profile#update",   as:   :update

  #   resources :images do
  #     member do
  #       put :crop
  #     end
  #   end
  # end

end

app/models/dashboard_widget.rb
class DashboardWidget < ActiveRecord::Base

  belongs_to :dashboard
  belongs_to :widget

  def savewidgets(widgets, dashboard)
    widgets.each do |wid|
      @dashboard_widget = DashboardWidget.new
      @dashboard_widget.widget_id = wid
      @dashboard_widget.dashboard_id = dashboard.id
      @dashboard_widget.save if @dashboard_widget.valid?
    end
  end
  
end

app/controllers/admin/dashboard_widgets_controller.rb
class Admin::DashboardWidgetsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :require_login

  def index
  end

  def new
    @dashboard = Dashboard.find_by_id params[:dashboard_id]
    @dw = DashboardWidget.all
    @dashboard_widget = DashboardWidget.new
    @widgets = Widget.all
    @github_widgets = @widgets.all.select{|w|w.name if w.widget_type=='Github' && w.name == 'Github-Open-PR'}
    @jira_widgets = @widgets.all.select{|w|w.name if w.widget_type=='Jira' && w.name != 'Jira Stories Details'}
    @code_widgets = @widgets.all.select{|w|w.name if w.widget_type=='Code Climate'}
    @jenkins_widgets = @widgets.all.select{|w|w.name if w.widget_type=='Jenkins'}
    @newreli_widgets = @widgets.all.select{|w|w.name if w.widget_type=='Newrelic'&& w.name != 'Response-Time'}
    @sonar_widgets = @widgets.all.select{|w|w.name if w.widget_type=='sonar'}
    @rally_widgets = @widgets.all.select{|w|w.name if w.widget_type=='rally'}
    @rally1_widgets = @widgets.all.select{|w|w.name if w.widget_type=='rally1'}
    @rally2_widgets = @widgets.all.select{|w|w.name if w.widget_type=='rally2'}

  end

  def create
    @dashboard = Dashboard.find_by_id params[:dashboard_id]
    @dashboard_widget = DashboardWidget.new
    if widget_params.present?
      @dashboard_widget.savewidgets(widget_params, @dashboard)
      @success = true
      flash[:success] = "Widgets added successfully!"
    else
      @success = false
    end
  end

  def edit
    @dashboard = Dashboard.find_by_id params[:dashboard_id]
    @widget = Widget.find_by_id params[:id]
    @dashboard_widget = DashboardWidget.find params[:widget_id]
  end

  def update
    @dashboard_widget = DashboardWidget.find_by_id(params[:id])
    @widget = Widget.find_by_id(@dashboard_widget.widget_id)
    @dashboard = Dashboard.find_by_id params[:dashboard_id]
    @dashboard_widget.access_token = params[:dashboard_widget][:access_token]
    @dashboard_widget.organization_name = params[:dashboard_widget][:organization_name]
    @dashboard_widget.repo_name = params[:dashboard_widget][:repo_name]
    @dashboard_widget.status = params[:dashboard_widget][:status]
    @dashboard_widget.github_url = params[:dashboard_widget][:github_url]
    @dashboard_widget.code_api_token = params[:dashboard_widget][:code_api_token]
    @dashboard_widget.code_repo_id = params[:dashboard_widget][:code_repo_id]
    @dashboard_widget.jira_url = params[:dashboard_widget][:jira_url]
    @dashboard_widget.jira_view_id = params[:dashboard_widget][:jira_view_id]
    @dashboard_widget.jira_name = params[:dashboard_widget][:jira_name]
    @dashboard_widget.jira_password = params[:dashboard_widget][:jira_password]
    @dashboard_widget.jira_project_key = params[:dashboard_widget][:jira_project_key]
    @dashboard_widget.github_status_prs = params[:dashboard_widget][:github_status_prs]
    @dashboard_widget.jenkins_name = params[:dashboard_widget][:jenkins_name]
    @dashboard_widget.jenkins_password = params[:dashboard_widget][:jenkins_password]
    @dashboard_widget.key = params[:dashboard_widget][:key]
    @dashboard_widget.sonar_server = params[:dashboard_widget][:sonar_server]
    @dashboard_widget.matric = params[:dashboard_widget][:matric ]
    @dashboard_widget.status = "configured"
    if @dashboard_widget.valid?
     @dashboard_widget.save
     @success = true
   else
     @success = false
   end
 end

 def destroy
  @dashboard = Dashboard.find_by_id params[:dashboard_id]
  @widget = Widget.find_by_id params[:id]
  @dashboard_widget = DashboardWidget.where(dashboard_id: @dashboard.id).find_by_widget_id(@widget.id)
  @dashboard_widget.destroy
  flash[:notice] = "Widget deleted successfully!"
end

def update_widgets
  dashboard = Dashboard.find_by_id params[:dashboard_id]
  if dashboard.present?
    params[:widget_ids].each do |widget_id|
      widget = Widget.find_by_id widget_id
      dashboard.widgets << dashboard if widget.present?
    end
  end
end

private

def resource_url(obj)
  url_for([:admin, obj])
end

def default_item_name
  "dashboard_widget"
end

def widget_params
  [params["gitwidget"],params["jirawidget"],params["codewidget"],params["jenkinswidget"],params["sonarwidget"],params["rallywidget"]].compact.reduce([], :|)
end

def set_navs
  set_nav("admin/dashboard_widgets")
end

end

app/views/admin/dashboard_widgets/_form.html.erb
<div id="popup_modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">                      
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Widgets</h4>
      </div>
      <%= form_for([:admin, @dashboard_widget], url: admin_dashboard_dashboard_widgets_path(@dashboard), :html => {:id=>"form_dashboard_widget", :method => :post, :remote=>true}) do |f| %>
      <div class="modal-body">
        <% dashwidgets = DashboardWidget.where(dashboard_id: @dashboard.id).pluck(:widget_id) %>
        <div class="row">
          <div class="col-sm-4 text-center" >
            <div class="modal-widgets">
              <div class="order-list selected" id="git">
                <a href="#" class="widget-name selected">GIT
                  <div class="num-widgets number-of-widgets">
                    <% @count = 0 %>
                    <% @github_widgets.each do |widget| %>
                    <% if dashwidgets.include?(widget.id) %>
                    <% @count += 1 %><% end %><% end %>
                    <%=  @count %> item(s) selected</div>
                  </a>
                </div>
                <div class="order-list" id="jira">
                  <a href="#" class="widget-name">JIRA
                    <div class="num-widgets number-of-widgets">
                      <% @count = 0 %>
                      <% @jira_widgets.each do |widget| %>
                      <% if dashwidgets.include?(widget.id) %>
                      <% @count += 1 %><% end %><% end %>
                      <%=  @count %> item(s) selected</div>
                    </a>
                  </div>
                  <div class="order-list" id="code">
                    <a href="#" class="widget-name">CODE CLIMATE
                      <div class="num-widgets number-of-widgets">
                        <% @count = 0 %>
                        <% @code_widgets.each do |widget| %>
                        <% if dashwidgets.include?(widget.id) %>
                        <% @count += 1 %><% end %><% end %>
                        <%=  @count %> item(s) selected</div>
                      </a>
                    </div>
                    <div class="order-list" id="jenkins">
                      <a href="#" class="widget-name">Jenkins
                        <div class="num-widgets number-of-widgets">
                          <% @count = 0 %>
                          <% @jenkins_widgets.each do |widget| %>
                          <% if dashwidgets.include?(widget.id) %>
                          <% @count += 1 %><% end %><% end %>
                          <%=  @count %> item(s) selected</div>
                        </a>
                      </div>
                      <div class="order-list" id="newrelic">
                        <a href="#" class="widget-name">Newrelic
                          <div class="num-widgets number-of-widgets">
                            <% @count = 0 %>
                            <% @newreli_widgets.each do |widget| %>
                            <% if dashwidgets.include?(widget.id) %>
                            <% @count += 1 %><% end %><% end %>
                            <%=  @count %> item(s) selected</div>
                          </a>
                        </div>
                        <div class="order-list" id="sonar">
                          <a href="#" class="widget-name">Sonar
                            <div class="num-widgets number-of-widgets">
                              <% @count = 0 %>
                              <% @sonar_widgets.each do |widget| %>
                              <% if dashwidgets.include?(widget.id) %>
                              <% @count += 1 %><% end %><% end %>
                              <%=  @count %> item(s) selected</div>
                            </a>
                          </div>
                          <div class="order-list" id="rally">
                          <a href="#" class="widget-name">Rally
                            <div class="num-widgets number-of-widgets">
                              <% @count = 0 %>
                              <% @rally_widgets.each do |widget| %>
                              <% if dashwidgets.include?(widget.id) %>
                              <% @count += 1 %><% end %><% end %>
                              <%=  @count %> item(s) selected</div>
                            </a>
                            
                          </div>
                          <div class="order-list" id="rally1">
                          <a href="#" class="widget-name">Rally1
                            <div class="num-widgets number-of-widgets">
                              <% @count = 0 %>
                              <% @rally1_widgets.each do |widget| %>
                              <% if dashwidgets.include?(widget.id) %>
                              <% @count += 1 %><% end %><% end %>
                              <%=  @count %> item(s) selected</div>
                            </a>
                          </div>
                          <div class="order-list" id="rally2">
                          <a href="#" class="widget-name">Rally2
                            <div class="num-widgets number-of-widgets">
                              <% @count = 0 %>
                              <% @rally2_widgets.each do |widget| %>
                              <% if dashwidgets.include?(widget.id) %>
                              <% @count += 1 %><% end %><% end %>
                              <%=  @count %> item(s) selected</div>
                            </a>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-8">
                        <div class="add-tiles-content">
                         <div class="checkbox" id="git-widget">
                          <div>
                            <% @github_widgets.each do |widget| %>
                            <% unless dashwidgets.include?(widget.id) %>
                            <div><%= check_box_tag "gitwidget[]", widget.id %><%= widget.name %></div>
                            <% else %>
                            <div><input type="checkbox" checked="checked" disabled="true"></div><%= widget.name %>
                            <% end %>
                            <% end %>
                          </div>
                        </div>
                        <div class="checkbox" id="jira-widget">
                          <div>
                            <% @jira_widgets.each do |widget| %>
                            <% unless dashwidgets.include?(widget.id) %>
                            <div><%= check_box_tag "jirawidget[]", widget.id %><%= widget.name %></div>
                            <% else %>
                            <div><input type="checkbox" checked="checked" disabled="true"></div><%= widget.name %>
                            <% end %>
                            <% end %>
                          </div>
                        </div>
                        <div class="checkbox" id="code-widget">
                          <div>
                            <% @code_widgets.each do |widget| %>
                            <% unless dashwidgets.include?(widget.id) %>
                            <div><%= check_box_tag "codewidget[]", widget.id %><%= widget.name %></div>
                            <% else %>
                            <div><input type="checkbox" checked="checked" disabled="true"></div><%= widget.name %>
                            <% end %>
                            <% end %>
                          </div>
                        </div>
                        <div class="checkbox" id="jenkins-widget">
                          <div>
                            <% @jenkins_widgets.each do |widget| %>
                            <% unless dashwidgets.include?(widget.id) %>
                            <div><%= check_box_tag "jirawidget[]", widget.id %><%= widget.name %></div>
                            <% else %>
                            <div><input type="checkbox" checked="checked" disabled="true"></div><%= widget.name %>
                            <% end %>
                            <% end %>
                          </div>
                        </div>
                        <div class="checkbox" id="newrelic-widget">
                          <div>
                            <% @newreli_widgets.each do |widget| %>
                            <% unless dashwidgets.include?(widget.id) %>
                            <div><%= check_box_tag "jirawidget[]", widget.id %><%= widget.name %></div>
                            <% else %>
                            <div><input type="checkbox" checked="checked" disabled="true"></div><%= widget.name %>
                            <% end %>
                            <% end %>
                          </div>
                        </div>
                        <div class="checkbox" id="sonar-widget">
                          <div>
                            <% @sonar_widgets.each do |widget| %>
                            <% unless dashwidgets.include?(widget.id) %>
                            <div><%= check_box_tag "sonarwidget[]", widget.id %><%= widget.name %></div>
                            <% else %>
                            <div><input type="checkbox" checked="checked" disabled="true"></div><%= widget.name %>
                            <% end %>
                            <% end %>
                          </div>
                        </div>



                        <div class="checkbox" id="rally-widget">
                          <div>
                            <% @rally_widgets.each do |widget| %>
                            <% unless dashwidgets.include?(widget.id) %>
                            <div><%= check_box_tag "rallywidget[]", widget.id %><%= widget.name %></div>
                            <% else %>
                            <div><input type="checkbox" checked="checked" disabled="true"></div><%= widget.name %>
                            <% end %>
                            <% end %>
                          </div>
                        </div>
                       <div class="checkbox" id="rally1-widget">
                          <div>
                            <% @rally1_widgets.each do |widget| %>
                            <% unless dashwidgets.include?(widget.id) %>
                            <div><%= check_box_tag "rallywidget[]", widget.id %><%= widget.name %></div>
                            <% else %>
                            <div><input type="checkbox" checked="checked" disabled="true"></div><%= widget.name %>
                            <% end %>
                            <% end %>
                          </div>
                        </div>
                        <div class="checkbox" id="rally2-widget">
                          <div>
                            <% @rally2_widgets.each do |widget| %>
                            <% unless dashwidgets.include?(widget.id) %>
                            <div><%= check_box_tag "rallywidget[]", widget.id %><%= widget.name %></div>
                            <% else %>
                            <div><input type="checkbox" checked="checked" disabled="true"></div><%= widget.name %>
                            <% end %>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  <%= f.submit "Save changes", :class=>"btn btn-primary", :id => "click_disable1" %>
                </div>
                <%end%>
              </div>
            </div>
          </div>
          <script type="text/javascript">
            $("#style1").addClass('ss');
            $('#jira-widget').hide();
            $('#code-widget').hide();
            $('#jenkins-widget').hide();
            $('#newrelic-widget').hide();
            $('#sonar-widget').hide();
            $('#rally-widget').hide();
            $('#rally1-widget').hide();
            $('#rally2-widget').hide();
            $(document).ready(function() {
              $('.widget-name').on('click', function(){
                $('.widget-name').removeClass('selected');
                $(this).addClass('selected');
              });
            });
            $(document).ready(function(){
              $("#click_disable1").click(function(){
                $("#click_disable1").addClass('disabled');
              });
            });
          </script>

app/views/admin/dashboard_widgets/create.js.erb
$('#div_dashboard_show').html("<%= escape_javascript(render(:partial=>'/admin/dashboards/show')) %>");
$('#d_flash_message').html("<%= escape_javascript(render(:partial=>'/layouts/dashing/flash_messages')) %>");
$('#div_wallboard_button').html("<%= escape_javascript(render(:partial=>'/admin/dashboards/wallboard_button')) %>");
$('.modal-backdrop').hide();
<% flash[:success] = nil %>

app/views/admin/dashboard_widgets/destroy.js.erb
$('#div_dashboard_show').html("<%= escape_javascript(render(:partial=>'/admin/dashboards/show')) %>");
$('#d_flash_message').html("<%= escape_javascript(render(:partial=>'/layouts/dashing/flash_messages')) %>");
$('#div_wallboard_button').html("<%= escape_javascript(render(:partial=>'/admin/dashboards/wallboard_button')) %>");
$('.modal-backdrop').hide();
<% flash[:notice] = nil %>

app/views/admin/dashboard_widgets/edit.js.erb
heading = "Configure Widget";
<% if @widget.widget_type == "Github" && @widget.name == "Github-Status" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/github/github_status'))  %>");
$('#myModal').modal('show');
<% elsif @widget.widget_type == "Github" && @widget.name == "Github-Open-PR" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/github/github_pr'))  %>");
$('#myModal').modal('show');
github_validator()
<% elsif @widget.widget_type == "Github" && @widget.name == "Github-Closed-PR" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/github/github_pr'))  %>");
$('#myModal').modal('show');
github_validator()
<% elsif @widget.widget_type == "Github" && @widget.name == "Github-Last-10-Commits" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/github/github_pr'))  %>");
$('#myModal').modal('show');
github_validator()
<% end %>


<% if @widget.widget_type == "Code Climate" && @widget.name == "GPA" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/codeclimate/code_climate'))  %>");
$('#myModal').modal('show');
code_gpa_validator()
<% elsif @widget.widget_type == "Code Climate" && @widget.name == "Test-coverage" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/codeclimate/code_climate'))  %>");
$('#myModal').modal('show');
code_gpa_validator()
<% end %>

<% if @widget.widget_type == "Jira" && @widget.name == "Sprint-remaning-days" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/jira/jira'))  %>");
$('#myModal').modal('show');
jira_validator()
<% elsif @widget.widget_type == "Jira" && @widget.name == "Sprint-progress" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/jira/jira_noofissues'))  %>");
$('#myModal').modal('show');
jira_validator()
<% elsif @widget.widget_type == "Jira" && @widget.name == "Jira Stories Details" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/jira/jira_noofissues'))  %>");
$('#myModal').modal('show');
jira_no_of_issues_validator()
<% elsif @widget.widget_type == "Jira" && @widget.name == "Burn Down Chart" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/jira/jira'))  %>");
$('#myModal').modal('show');
jira_validator()
<% end %>

<% if @widget.widget_type == "Jenkins" && @widget.name == "Build-test" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/jenkins/jenkins_build_status'))  %>");
$('#myModal').modal('show');
jira_no_of_issues_validator()
<% end %>




<% if @widget.widget_type == "rally" && @widget.name == "rally" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/rally/rally'))  %>");
$('#myModal').modal('show');
jira_validator()
<% elsif @widget.widget_type == "rally1" && @widget.name == "rally1" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/rally/rally1'))  %>");
$('#myModal').modal('show');

<% elsif @widget.widget_type == "rally2" && @widget.name == "rally2" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/rally/rally2'))  %>");
$('#myModal').modal('show');


<% end %>







<% if @widget.widget_type == "sonar" && @widget.name == "sonar" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/sonar/sonar'))  %>");
$('#myModal').modal('show');
sonar_validator()
<%end%>


<% if @widget.widget_type == "Newrelic" && @widget.name == "Error-Rate" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/newrelic/newrelic'))  %>");
$('#myModal').modal('show');
jira_validator()
<% elsif @widget.widget_type == "Newrelic" && @widget.name == "Response-Time" %>
$('#myModal').html("<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/newrelic/newrelic'))  %>");
$('#myModal').modal('show');
jira_no_of_issues_validator()
<% end %>

app/views/admin/dashboard_widgets/update.js.erb
<% if @success %>
$('#div_dashboard_show').html("<%= escape_javascript(render(:partial=>'/admin/dashboards/show')) %>");
$('#div_wallboard_button').html("<%= escape_javascript(render(:partial=>'/admin/dashboards/wallboard_button')) %>");
$('.modal-backdrop').hide();
<% else %>
heading = "Configure Widget";
<% if @widget.widget_type == "Github" && @widget.name == "Github-Status" %>
bodyContent = "<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/github/github_status')) %>";
showModal(heading, bodyContent);
<% elsif @widget.widget_type == "Github" && @widget.name == "Github-Open-PR" %>
bodyContent = "<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/github/github_openPR')) %>";
showModal(heading, bodyContent);
<% elsif @widget.widget_type == "Github" && @widget.name == "Github-Closed-PR" %>
bodyContent = "<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/github/github_closedPR')) %>";
showModal(heading, bodyContent);
<% elsif @widget.widget_type == "Github" && @widget.name == "Github-Last-10-Commits" %>
bodyContent = "<%= escape_javascript(render(:partial=>'/admin/dashboard_widgets/github/github_commits')) %>";
showModal(heading, bodyContent);
<% end %>
<% end %>