config/routes.rb
Rails.application.routes.draw do
  mount Dashing::Engine, at: Dashing.config.engine_path
  root :to => 'admin/sessions#index'
  get 'users/unique_email' => 'admin/users#unique_email'
  # get "log_in" => "users#new", :as => "log_in"

  # Sign In URLs for users
  # get     '/sign_in',         to: "public/user_sessions#sign_in",         as:  :sign_in
  # post    '/create_session',  to: "public/user_sessions#create_session",  as:  :create_session
  # Logout Url
  # delete  '/sign_out' ,       to: "public/user_sessions#sign_out",        as:  :sign_out

  namespace :admin do
    resources :users
    resources :sessions
    resources :birthdays
    resources :events
    resources :generals
    resources :newjoiners
    resources :anniversarrys
    resources :achievements
    resources :hrs 
    resources :wallboards
      
    get :admin_role
    resources :dashboards do
      mount Dashing::Engine, at: Dashing.config.engine_path
      resources :dashboard_widgets
    end
  end
  # post "pop_up" => "admin/dashboards#pop_up"
  # ------------
  # User pages
  # ------------

  # namespace :users do
  #   get   '/dashboard',         to: "dashboard#index",  as:   :dashboard
  #   get   '/profile',           to: "profile#index",    as:   :profile
  #   get   '/edit',              to: "profile#edit",     as:   :edit
  #   put   '/update',            to: "profile#update",   as:   :update

  #   resources :images do
  #     member do
  #       put :crop
  #     end
  #   end
  # end

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base

	has_many :dashboard_widgets
	has_many :widgets, through: :dashboard_widgets
	validates :name, presence: true
	validates_uniqueness_of :name
end

app/controllers/admin/dashboards_controller.rb
 class Admin::DashboardsController < ApplicationController
  before_filter :require_login

  def index
    get_collections
  end

  def new
    @dashboard = Dashboard.new
  end

  def create
    @dashboard = Dashboard.new(dashboard_params)
    if @dashboard.valid?
      @dashboard.save
      @success = true
      flash[:success] = "Dashboard created successfully!"
    else
      @success = false
    end
    @dashboards = Dashboard.order("updated_at desc").paginate(:page => params[:page], :per_page => 4)
  end

  def edit
    @dashboard = Dashboard.find(params[:id])
  end

  def show
    @dashboard = Dashboard.find(params[:id])
  end

  def update
    @dashboard = Dashboard.find(params[:id])
    @dashboards = Dashboard.order("updated_at desc").paginate(:page => params[:page], :per_page => 4)
    @dashboard.update_attributes(dashboard_params)
    if @dashboard.valid?
      @success = true
      flash[:success] = "Dashboard updated successfully!"
    else
      @success = false
    end
  end

  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboardwidgets = DashboardWidget.where(dashboard_id: params[:id])
    @dashboardwidgets.destroy_all
    @dashboard.destroy
    @dashboards = Dashboard.order("updated_at desc").paginate(:page => params[:page], :per_page => 4)
    redirect_to admin_dashboards_path
    flash[:notice] = "Dashboard deleted successfully!"
  end

  private

  def dashboard_params
    params[:dashboard].permit(:name)
  end

  def get_collections
    # Fetching the dashboard
    relation = Dashboard.where("")
    @filters = {}
    if params[:query]
      @query = params[:query].strip
      relation = relation.search(@query) if !@query.blank?
    end
    @dashboards = relation.order("updated_at desc")
    @dashboards = Dashboard.order("updated_at desc").paginate(:page => params[:page], :per_page => 4)
    ## Initializing the @dashboard object so that we can render the show partial
    @dashboard = @dashboards.first unless @dashboard
    return true
  end

end

app/controllers/dashing/dashboards_controller.rb
module Dashing
  class DashboardsController < ApplicationController
    require 'octokit'
    require 'httparty'
    require 'net/http'
    require 'json'
    require 'jira'
    require 'time'
    require 'newrelic_api'
    require 'open-uri'
    require 'cgi'

    include GitHub
    include CodeClimate
    include Jira
    include Jenkins
    include Newrelic
    include BurnDownChart
    include QwinixUpdatesJob

    before_filter :check_dashboard_name, only: :show

    rescue_from ActionView::MissingTemplate, with: :template_not_found

    def index
      get_the_job_done(params[:dashboard_id])
      render file: dashboard_path(Dashing.config.default_dashboard || Dashing.first_dashboard || ''), layout: Dashing.config.dashboard_layout_path
    end

    def show
      render file: dashboard_path(params[:name]), layout: Dashing.config.dashboard_layout_path
    end

    private

    def check_dashboard_name
      raise 'bad dashboard name' unless params[:name] =~ /\A[a-zA-z0-9_\-]+\z/
    end

    def dashboard_path(name)
      Dashing.config.dashboards_views_path.join(name)
    end

    def template_not_found
      raise "Count not find template for dashboard '#{params[:name]}'. Define your dashboard in #{dashboard_path('')}"
    end

    def get_the_job_done(id)
      @json_obj = []
      if id != nil
        dashboard = Dashboard.find id
        dashboard.dashboard_widgets.each do |dash_wid|
          @json_obj << JSON.parse(dash_wid.to_json).compact
        end   
        @json_obj.each do |obj|
          case (Widget.find obj["widget_id"]).name 
          when "Github-Open-PR" 
            github_open_pr_job(obj) if obj["status"] == "configured"
          when "Github-Closed-PR" 
            github_closed_pr_job(obj) if obj["status"] == "configured"
          when "GPA" 
            gpa(obj) if obj["status"] == "configured"
          when "Github-Status" 
            github_status(obj) if obj["status"] == "configured"
          when "Sprint-progress" 
            sprint_progress(obj) if obj["status"] == "configured"
          when "Sprint-remaning-days" 
            sprint_remaining_days(obj) if obj["status"] == "configured"
          when "Jira Stories Details" 
            number_of_open_issues(obj) if obj["status"] == "configured" 
          when "Build-test" 
            jenkins_build_status(obj) if obj["status"] == "configured"
          when "Github-Last-10-Commits" 
            github_commits(obj) if obj["status"] == "configured"
          when "Error-Rate" 
            newrelic_job(obj) if obj["status"] == "configured"
          when "Response-Time" 
            newrelic_job(obj) if obj["status"] == "configured"
          when "Burn Down Chart" 
            BurnDown.burn_down_chart(obj) if obj["status"] == "configured"
          end
        end
      else
       view_qwinix_updates
      end
    end
  end
end

app/views/admin/dashboards/_form.html.erb
 <div class="row">
    <div class="col-sm-offset-2 col-sm-10">
    <%= form_for([:admin, @dashboard], :html => {:id=>"form_dashboard", :remote=>true}) do |f| %>
 <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New Dashboard</h3>
  </div>
  <div class="panel-body" style="height:auto;">
    <div id="dashboard_form_error">
      <%= @dashboard.errors[:base].to_sentence %>
    </div>
    <div class="form-group">
      <label for="inputName" class="col-sm-3 control-label">Name *</label>
      <div class="col-sm-9">
        <%= f.text_field :name, :class=>"form-control", :id=>"inputName", :placeholder=>"Name" %>
        <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @dashboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
      </div>
    </div>
  </div>
  <div class="panel-footer text-right">
    <%= link_to "Cancel", admin_dashboards_path, :class => "btn btn-default", remote: true %>
    <!-- Button trigger modal -->
    <%= f.submit "OK", :class => "btn btn-primary" %>

  </div>
  <!-- </div> -->
  <% end %>
  </div>
  </div>
  </div>

app/views/admin/dashboards/_index.html.erb
<% @dashboards.each do |dashboard| %>
<div class="col-sm-offset-1 col-sm-10">
  <div class="dashbords">
<%= link_to admin_dashboard_path(dashboard),remote: true do %>
    <div class="tiles btn btn-default">
      <%= dashboard.name %>
    </div>
<% end %>
  </div>
</div>
<%end%>
<div class="col-sm-offset-1 col-sm-10">
<%= will_paginate @dashboards, renderer: BootstrapPagination::Rails, :next_label => '>',:previous_label => '<',:inner_window   => 0, :outer_window => 0 %>
</div>

app/views/admin/dashboards/_show.html.erb
 <div class="row">
  <div class="col-sm-offset-2 col-sm-10">
    <div class="new-widget-area">
      <div class="title"><%= @dashboard.name %></div>
      <div class="row customs">
        <div class="col-sm-7">
          <i class="fa fa-plus"></i>
          <%= link_to  "Add New Widgets ",new_admin_dashboard_dashboard_widget_path(@dashboard), :remote=>true, 'data-toggle'=>"modal", 'data-target'=>"#myModal" %>
        </div>
        <div class="col-sm-5 text-right">
          <i class="fa fa-trash"></i>
          <%= link_to "Delete", admin_dashboard_path(@dashboard), method: :delete, data: { confirm: 'Data cannot be retained back if deleted. Are you sure you want to delete the dashboard?' } %>
          <i class="fa fa-pencil-square-o"></i>
          <%= link_to "Edit", edit_admin_dashboard_path(@dashboard), :remote=>true %>
        </div>
      </div>
      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      </div>
    </div>
    <div id="d_flash_message" class="flash">
    </div>
    <!-- Selected widgets -->
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Selected widgets</h3>
      </div>
      <%  @widgets = DashboardWidget.where(:dashboard_id => @dashboard.id) %>
      <% if @widgets.any? %>
      <div class="panel-body selected-widgets-area">
        <% @widgets.each do |w|%>
        <div class="row tiles">
          <div class="col-sm-7">
            <a><%= Widget.find(w.widget_id).widget_type %> - <%= Widget.find(w.widget_id).name %></a>
          </div>
          <div class="col-sm-5 text-right">
            <i class="fa fa-trash"></i> <%= link_to "Delete", admin_dashboard_dashboard_widget_path(@dashboard, w.widget_id), method: :delete, data: { confirm: "Are you sure you want to delete the widget?" }, :remote=>true %>
            <a data-toggle="modal" data-target="#myModal"><%= link_to "Configure", edit_admin_dashboard_dashboard_widget_path(@dashboard, w.widget_id, widget_id: w.id), :remote=>true %></a>
            <% if w.status == "configured" %><i style="color:green;">&#10004;</i><% end %>
          </div>
        </div>
        <%  end %>
        <% else %>
        <center>No Widgets</center>
        <% end%>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  setTimeout(function(){
    $('.flash').remove();
  }, 5000);
</script>

app/views/admin/dashboards/_wallboard_button.html.erb
<div class="text-right dash-btn-group">
  <%= link_to 'Add New Dashboard', new_admin_dashboard_path, :remote => true, :class=>"btn btn-primary" %>
  <%= link_to 'Wallboard', admin_dashboard_dashing_path(@dashboard), :class=>"btn btn-primary", :target=>"_blank", :disabled => !(DashboardWidget.where(dashboard_id: @dashboard.id).pluck(:status).include?("configured")) if @dashboard %>
</div>

app/views/admin/dashboards/_widgets.js.erb
heading = "List of widgets";
bodyContent = "<%= escape_javascript(render(:partial=>'admin/dasboards/widgets.html.erb', locals: {redirect_back_url: request.original_url})) %>";
showModal(heading, bodyContent);

app/views/admin/dashboards/create.js.erb
<% if @success %>
window.location.href = "/admin/dashboards"
<% else %>
$('#div_dashboard_show').html("<%= escape_javascript(render(:partial=>'form')) %>");
  // Populate Server Side Errors
  <%
  text = "You have few errors. They have been highlighted."
  error_message = content_tag(:div, text, class: "alert alert-danger")
  %>
  $("#dashboard__error").html("<%= escape_javascript(error_message) %>");
  <% end %>

app/views/admin/dashboards/edit.js.erb
$('#div_dashboard_show').html("<%= escape_javascript(render(:partial=>'form')) %>");

app/views/admin/dashboards/index.html.erb
<div class="page-title">
  Manage Dashboards
</div>
<div id="div_flash_message">
    <%= render :partial=>"/layouts/dashing/flash_messages" -%>
</div>
<div class="container">
<div id="div_wallboard_button">
    <%= render :partial=>"wallboard_button" %>
  </div>
<% if @dashboards.present? %>
<div class="row dashboard_index">
  <div id="div_dashboard_index" class="col-sm-6 hidden-xs">
    <%= render :partial=>"index" %>
  </div>
  <div id="div_dashboard_show" class="col-xs-12 col-sm-6">
    <%= render :partial=>"show", locals: {:dashboard => @dashboard } %>
  </div>
</div>
<% else %>
<div class="row dashboard_index">
  <div id="div_dashboard_index" class="col-sm-6 hidden-xs">
    <div class="nodashboard">Nothing to display</div>
  </div>
  <div id="div_dashboard_show" class="col-xs-12 col-sm-6">
  </div>
</div>
<% end %>
</div>

app/views/admin/dashboards/index.js.erb
<% if @dashboards.any? %>
  // Fill the right box with first dashboard details in the list
  $('#div_dashboard_show').html("<%= escape_javascript(render(:partial=>'show')) %>");
  initPopovers();

  // Rendering the item list
  $('#div_dashboard_index').html("<%= escape_javascript(render(:partial=>'index')) %>");
<% else %>
  var noResultsText = "<%= escape_javascript(theme_panel_message(I18n.translate('forms.no_results')))%>";
  $('#div_dashboard_index').html(noResultsText);
  $('#div_dashboard_show').html(noResultsText);
  $('#div_dashboard_details').html("");
<% end %>

app/views/admin/dashboards/new.js.erb
$('#div_dashboard_show').html("<%= escape_javascript(render(:partial=>'form')) %>");
$('#div_dashboard_details').html("");

app/views/admin/dashboards/show.js.erb
$('#div_dashboard_show').html("<%= escape_javascript(render(:partial=>'show')) %>");
$('#div_wallboard_button').html("<%= escape_javascript(render(:partial=>'/admin/dashboards/wallboard_button')) %>");

app/views/admin/dashboards/update.js.erb
<% if @success %>
  window.location.href = "/admin/dashboards"
<% else %>
  $('#div_dashboard_show').html("<%= escape_javascript(render(:partial=>'form')) %>");

  // Populate Server Side Errors
  <%
    text = "You have few errors. They have been highlighted."
    error_message = content_tag(:div, text, class: "alert alert-danger")
  %>
  $("#dashboard__error").html("<%= escape_javascript(error_message) %>");
<% end %>

app/views/admin/dashboards/widgets.html.erb
<div class="panel panel-default panel-bordered panel-420 p-20">

  <%= image_tag("dish_dash_logo.jpg", class: "centered", alt: "Dish Dash Logo") %>

  <hr/>

  <%= render partial: "admin/dasboards/widgets.html.erb" %>

</div>

<div class="cl"></div>