config/routes.rb
Rails.application.routes.draw do
  mount Dashing::Engine, at: Dashing.config.engine_path
  root :to => 'admin/sessions#index'
  get 'users/unique_email' => 'admin/users#unique_email'
  # get "log_in" => "users#new", :as => "log_in"

  # Sign In URLs for users
  # get     '/sign_in',         to: "public/user_sessions#sign_in",         as:  :sign_in
  # post    '/create_session',  to: "public/user_sessions#create_session",  as:  :create_session
  # Logout Url
  # delete  '/sign_out' ,       to: "public/user_sessions#sign_out",        as:  :sign_out

  namespace :admin do
    resources :users
    resources :sessions
    resources :birthdays
    resources :events
    resources :generals
    resources :newjoiners
    resources :anniversarrys
    resources :achievements
    resources :hrs 
    resources :wallboards
      
    get :admin_role
    resources :dashboards do
      mount Dashing::Engine, at: Dashing.config.engine_path
      resources :dashboard_widgets
    end
  end
  # post "pop_up" => "admin/dashboards#pop_up"
  # ------------
  # User pages
  # ------------

  # namespace :users do
  #   get   '/dashboard',         to: "dashboard#index",  as:   :dashboard
  #   get   '/profile',           to: "profile#index",    as:   :profile
  #   get   '/edit',              to: "profile#edit",     as:   :edit
  #   put   '/update',            to: "profile#update",   as:   :update

  #   resources :images do
  #     member do
  #       put :crop
  #     end
  #   end
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
	has_secure_password

	def self.authenticate(email, password)
		user = find_by_email(email)
		if user && user.password_digest == BCrypt::Engine.hash_secret(password, user.password_digest)
			user
		else
			nil
		end
	end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :require_login

	def index
		@users = User.order("created_at desc").paginate(:page => params[:page], :per_page => 3)
  end

  def unique_email
    @user = User.find_by_email(params[:user][:email])
    respond_to do |format|
      format.json { render :json => !@user }
    end
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.add_role :admin
      @user.save
      @success = true
    else
     @success = false
   end
 end

 private

 def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end
end

app/views/admin/users/_form.html.erb
 <div class="row">
  <div class="col-sm-offset-2 col-sm-10">
    <%= form_for :user, :url => admin_users_path, :method => :post, :html => {:id => "create_user",:remote => true} do |f| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New User</h3>
      </div>
      <div class="panel-body" style="height:auto;">
        <div class="form-group">
          <label for="inputName" class="col-sm-4 control-label">Name *</label>
          <div class="col-sm-8">
            <%= f.text_field :name, :class=>"form-control name",  :placeholder=>"Name" %>
          </div>
        </div><br><br>       
        <div class="form-group">
          <label for="inputName" class="col-sm-4 control-label">Email *</label>
          <div class="col-sm-8">
            <%= f.text_field :email, :class=>"form-control email",  :placeholder=>"Email" %>
          </div>
        </div><br><br>
        <div class="form-group">
          <label for="inputName" class="col-sm-4 control-label">Password *</label>
          <div class="col-sm-8">
            <%= f.password_field :password, :class=>"form-control password",  :placeholder=>"Password" %>
          </div>
        </div><br><br>
        <div class="form-group">
          <label for="inputName" class="col-sm-4 control-label">Password Confirmation *</label>
          <div class="col-sm-8">
            <%= f.password_field :password_confirmation, :class=>"form-control password_confirmation",  :placeholder=>"Password Confirmation" %>
          </div>
        </div>
      </div>
      <div class="panel-footer text-right">
        <%= link_to "Cancel", admin_users_path, :class => "btn btn-default", remote: true %>
        <%= f.submit "OK", :id => "click_disable1", :class => "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $("#click_disable1").click(function(){
      var val1 = $('.name').valid();
      var val2 = $('.email').valid();
      var val3 = $('.password').valid();
      var val4 = $('.password_confirmation').valid();
      if (val1 && val2 && val3 && val4) {
        $("#click_disable1").addClass('disabled');
      }
    });
  });
</script>

app/views/admin/users/_show.html.erb
<div class="col-sm-offset-1">
<div class="row">
  <!-- Dashboard tiles section -->
  <div class="col-sm-9">
  <% @users.each do |user|%>
    <div class="dashbords ">
      <div class="tiles">
        <%= user.name %>
      </div>
    </div>
<% end %>
  </div>
</div>
<%= will_paginate @users, renderer: BootstrapPagination::Rails, :next_label => '>',:previous_label => '<',:inner_window   => 0, :outer_window => 0  %>
</div>

app/views/admin/users/create.js.erb
<% if @success %>
window.location.reload();
<% else %>
<% end %>

app/views/admin/users/index.html.erb
<div class="page-title">
  Manage Users
</div>
<div class="container">
<div class="text-right dash-btn-group">
  <%= link_to 'Add New User', new_admin_user_path, :remote => true, :class=>"btn btn-primary" %>
</div>
<div class="row dashboard_index">
  <div id="div_dashboard_index" class="col-sm-6 hidden-xs">
    <%= render :partial=>"show" %>
  </div>
  <div id="div_dashboard_show" class="col-xs-12 col-sm-6">
    <%#= render :partial=>"", locals: {:dashboard => @dashboard } %>
  </div>
</div>
</div>

app/views/admin/users/index.js.erb
$('#div_dashboard_show').html("<%= escape_javascript(render(:partial=>'user')) %>");

app/views/admin/users/new.js.erb
$('#div_dashboard_show').html("<%= escape_javascript(render(:partial=>'form')) %>");
CreateUserValidator()